apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # BASE64 enconding:  echo -n '<plain-text>' | base64
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
